apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api-1
  template:
    metadata:
      labels:
        app: api-1
    spec:
      containers:
      - image: nginx:latest
        name: api-1
        ports:
        - containerPort: 80
