apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - image: nginx:latest
        name: api-2
        ports:
	- containerPort: 80
